# syntax=docker/dockerfile:1
FROM node:22-slim AS build
RUN corepack enable
WORKDIR /app
COPY web_ui/package.json web_ui/yarn.lock* ./
RUN yarn install --frozen-lockfile || yarn install
COPY web_ui ./
RUN yarn build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/templates/default.conf.template
EXPOSE 80
