#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Element {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Fe,
    Cu,
    Zn,
    Ag,
    I,
    Ba,
    Pt,
    Au,
    Hg,
    Pb,
}

impl Element {
    pub fn symbol(self) -> &'static str {
        match self {
            Element::H => "H",
            Element::He => "He",
            Element::Li => "Li",
            Element::Be => "Be",
            Element::B => "B",
            Element::C => "C",
            Element::N => "N",
            Element::O => "O",
            Element::F => "F",
            Element::Ne => "Ne",
            Element::Na => "Na",
            Element::Mg => "Mg",
            Element::Al => "Al",
            Element::Si => "Si",
            Element::P => "P",
            Element::S => "S",
            Element::Cl => "Cl",
            Element::Ar => "Ar",
            Element::K => "K",
            Element::Ca => "Ca",
            Element::Fe => "Fe",
            Element::Cu => "Cu",
            Element::Zn => "Zn",
            Element::Ag => "Ag",
            Element::I => "I",
            Element::Ba => "Ba",
            Element::Pt => "Pt",
            Element::Au => "Au",
            Element::Hg => "Hg",
            Element::Pb => "Pb",
        }
    }

    pub fn atomic_number(self) -> u8 {
        match self {
            Element::H => 1,
            Element::He => 2,
            Element::Li => 3,
            Element::Be => 4,
            Element::B => 5,
            Element::C => 6,
            Element::N => 7,
            Element::O => 8,
            Element::F => 9,
            Element::Ne => 10,
            Element::Na => 11,
            Element::Mg => 12,
            Element::Al => 13,
            Element::Si => 14,
            Element::P => 15,
            Element::S => 16,
            Element::Cl => 17,
            Element::Ar => 18,
            Element::K => 19,
            Element::Ca => 20,
            Element::Fe => 26,
            Element::Cu => 29,
            Element::Zn => 30,
            Element::Ag => 47,
            Element::I => 53,
            Element::Ba => 56,
            Element::Pt => 78,
            Element::Au => 79,
            Element::Hg => 80,
            Element::Pb => 82,
        }
    }

    /// Standard atomic weight, g/mol
    pub fn atomic_mass(self) -> f64 {
        match self {
            Element::H => 1.008,
            Element::He => 4.0026,
            Element::Li => 6.94,
            Element::Be => 9.0122,
            Element::B => 10.81,
            Element::C => 12.011,
            Element::N => 14.007,
            Element::O => 15.999,
            Element::F => 18.998,
            Element::Ne => 20.180,
            Element::Na => 22.990,
            Element::Mg => 24.305,
            Element::Al => 26.982,
            Element::Si => 28.085,
            Element::P => 30.974,
            Element::S => 32.06,
            Element::Cl => 35.45,
            Element::Ar => 39.948,
            Element::K => 39.098,
            Element::Ca => 40.078,
            Element::Fe => 55.845,
            Element::Cu => 63.546,
            Element::Zn => 65.38,
            Element::Ag => 107.868,
            Element::I => 126.904,
            Element::Ba => 137.327,
            Element::Pt => 195.084,
            Element::Au => 196.967,
            Element::Hg => 200.592,
            Element::Pb => 207.2,
        }
    }

    pub fn from_symbol(s: &str) -> Option<Self> {
        match s {
            "H" => Some(Element::H),
            "He" => Some(Element::He),
            "Li" => Some(Element::Li),
            "Be" => Some(Element::Be),
            "B" => Some(Element::B),
            "C" => Some(Element::C),
            "N" => Some(Element::N),
            "O" => Some(Element::O),
            "F" => Some(Element::F),
            "Ne" => Some(Element::Ne),
            "Na" => Some(Element::Na),
            "Mg" => Some(Element::Mg),
            "Al" => Some(Element::Al),
            "Si" => Some(Element::Si),
            "P" => Some(Element::P),
            "S" => Some(Element::S),
            "Cl" => Some(Element::Cl),
            "Ar" => Some(Element::Ar),
            "K" => Some(Element::K),
            "Ca" => Some(Element::Ca),
            "Fe" => Some(Element::Fe),
            "Cu" => Some(Element::Cu),
            "Zn" => Some(Element::Zn),
            "Ag" => Some(Element::Ag),
            "I" => Some(Element::I),
            "Ba" => Some(Element::Ba),
            "Pt" => Some(Element::Pt),
            "Au" => Some(Element::Au),
            "Hg" => Some(Element::Hg),
            "Pb" => Some(Element::Pb),
            _ => None,
        }
    }
}
