[package]
name = "manager-rs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-agent = { workspace = true }
git-rs = { workspace = true }
proto-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ureq = { workspace = true }

[lints]
workspace = true
